//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GestorFactura.bdventa
{

    [Persistent(@"detalle")]
    public partial class Detalle : XPLiteObject
    {
        int fiddetalle;
        [Key(true)]
        public int iddetalle
        {
            get { return fiddetalle; }
            set { SetPropertyValue<int>(nameof(iddetalle), ref fiddetalle, value); }
        }
        int fcantidad;
        public int cantidad
        {
            get { return fcantidad; }
            set { SetPropertyValue<int>(nameof(cantidad), ref fcantidad, value); }
        }
        float fsubtotal;
        public float subtotal
        {
            get { return fsubtotal; }
            set { SetPropertyValue<float>(nameof(subtotal), ref fsubtotal, value); }
        }
        Producto fproducto_idproducto;
        [Association(@"DetalleReferencesProducto")]
        public Producto producto_idproducto
        {
            get { return fproducto_idproducto; }
            set { SetPropertyValue<Producto>(nameof(producto_idproducto), ref fproducto_idproducto, value); }
        }
        Venta fventa_idventa;
        [Association(@"DetalleReferencesVenta")]
        public Venta venta_idventa
        {
            get { return fventa_idventa; }
            set { SetPropertyValue<Venta>(nameof(venta_idventa), ref fventa_idventa, value); }
        }
    }

}
